title: socratools - Soundcraft audio mixer tools for Linux
theme: jekyll-theme-minimal
logo: /images/socratools.svg
github:
    is_user_page: false
    is_project_page: true
    repository_url: https://github.com/socratools/socranop
    repository_nwo: socratools/socranop
    owner_url: https://github.com/socratools
    owner_name: The socratools team
